Задание на повторение материала

    Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно



In [1]:
import numpy as np

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

 Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [3]:
a.reshape(2, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [4]:
a.reshape(6, 2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [5]:
a.reshape(3, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
a.reshape(4, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух -

In [7]:
a.reshape(6, -1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [8]:
a.reshape(-1, 6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a.reshape(-1, 3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [10]:
a.reshape(-1, 4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [11]:
b = a.reshape(12, -1)
b

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [12]:
np.linalg.matrix_rank(b)

1

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой 
 из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
 Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [65]:
c = np.random.randn(3, 4)
c

array([[-0.82823234, -0.24667584,  0.79808989, -0.04610045],
       [-0.14837592,  0.39187831,  0.04555608, -0.7292809 ],
       [ 1.12368576, -2.18421177,  0.31594878,  1.3314934 ]])

In [66]:
c.mean()

-0.014685417343696957

In [67]:
c.std()

0.9128235315298764

In [68]:
c.size

12

In [69]:
c = c.flatten()
c

array([-0.82823234, -0.24667584,  0.79808989, -0.04610045, -0.14837592,
        0.39187831,  0.04555608, -0.7292809 ,  1.12368576, -2.18421177,
        0.31594878,  1.3314934 ])

In [70]:
c.size

12

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [71]:
b = np.arange(0, 22, 2)
a = b[:0:-1]
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, 
 убывающих от 20 до 1 невключительно с интервалом 2. 
 В чем разница между массивами a и b?

In [72]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [73]:
a.shape

(10,)

In [74]:
b.shape

(1, 10)

Вертикально соединить массивы a и b. 
 a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, 
чем число строк двумерного массива b, состоящего из единиц. 
Итоговый массив v должен иметь атрибут size, равный 10.

In [75]:
a = np.zeros((2, 2))
a

array([[0., 0.],
       [0., 0.]])

In [76]:
b = np.ones((3, 2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [77]:
v = np.vstack((a, b))
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [78]:
v.size

10

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
 Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), 
 состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. 
 Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. 
 Какой размер имеет матрица B? 
 Получится ли вычислить обратную матрицу для матрицы B и почему?

In [79]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [81]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [82]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [83]:
B.size

16

In [84]:
B_inv = np.linalg.inv(B)
B_inv

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [85]:
# Не получается инвертировать матрицу, хотя матрица и имеет размер 4 * 4.
# Почему не понимаю.

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [92]:
np.random.seed(42)
np.random.randint(0, 10, 3)

array([6, 3, 7])

Создайте одномерный массив c, составленный из последовательности 
 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [93]:
c = np.random.randint(0, 16, 16)
c

array([12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7,  7,  2,  5,  4])

Поменяйте его форму так, чтобы получилась квадратная матрица C. 
 Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. 
 Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [94]:
C = c.reshape(4, 4)
C

array([[12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7],
       [ 7,  2,  5,  4]])

In [95]:
D = C * 10 + B
D

array([[125,  54,  83, 122],
       [ 34, 110, 186, 222],
       [ 93, 126, 179, 282],
       [102, 142, 262, 342]])

In [96]:
np.linalg.det(D)

-23916799.999999993

In [97]:
np.linalg.matrix_rank(D)

4

In [100]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.01146976, -0.00043819, -0.00342855, -0.00098006],
       [ 0.01503211,  0.04559807,  0.0153666 , -0.04763179],
       [ 0.00637209,  0.01086767, -0.02412697,  0.01056663],
       [-0.01454375, -0.02712737,  0.0131255 ,  0.01489831]])

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 
 Убедитесь, что в матрице D_inv остались только нули и единицы. 
 С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - 
 в качестве источников данных, получите матрицу E размером 4x4.  
 Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, 
 должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых 
соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [102]:
D_inv = np.where((0 < D_inv)&(D_inv > 0), 1, 0)
D_inv

array([[1, 0, 0, 0],
       [1, 1, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 1, 1]])

In [104]:
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [105]:
C

array([[12,  4,  6,  9],
       [ 2,  6, 10, 10],
       [ 7,  4,  3,  7],
       [ 7,  2,  5,  4]])

In [106]:
E = np.where([D_inv == 1], B, C)
E

array([[[  5,   4,   6,   9],
        [ 14,  50,  86,  10],
        [ 23,  86,   3, 212],
        [  7,   2, 212, 302]]])